### ISSUE TITLE
[error] ReferenceError: callback is not defined | [red] Uncaught Exception every 24h

### ISSUE THREAD

**Issue by AFI4711** [guidone/node-red-contrib-netatmo-dashboard#29]
Every 24h node-red restarted because of the following error:

`
15 Dec 04:18:49 - [red] Uncaught Exception:
15 Dec 04:18:49 - [error] ReferenceError: callback is not defined
    at ClientRequest.<anonymous> (/data/node_modules/node-red-contrib-netatmo-dashboard/netatmo-dashboard.js:46:9)
    at ClientRequest.emit (events.js:314:20) 
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ctnodered@1.5.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctnodered@1.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2023-12-15T03_18_49_565Z-debug.log
Starting dbus daemon
Starting Avahi daemon
Starting Node-Red
`
Is there a function missing in _netatmo-dashboard.js_ ?

`const callRefreshToken = ({ clientId, clientSecret, refreshToken }) => {
  return new Promise((resolve, reject) => {

    const responseEncoding = 'utf8';
    const httpOptions = {
      hostname: 'api.netatmo.com',
      port: '443',
      path: '/oauth2/token',
      method: 'POST',
      headers: { "Content-Type": "application/x-www-form-urlencoded" }
    };
    httpOptions.headers['User-Agent'] = 'node ' + process.version;

    const request = httpTransport.request(httpOptions, (res) => {
      let responseBufs = [];
      let responseStr = '';

      res.on('data', (chunk) => {
        if (Buffer.isBuffer(chunk)) {
          responseBufs.push(chunk);
        }
        else {
          responseStr = responseStr + chunk;
        }
      }).on('end', () => {
        responseStr = responseBufs.length > 0 ? Buffer.concat(responseBufs).toString(responseEncoding) : responseStr;
        if (res.statusCode === 200) {
          let json;
          try {
            json = JSON.parse(responseStr);
            resolve(json.access_token);
          } catch (e) {
            reject(e);
          }
        } else {
          reject('Unable to refresh the access token');
        }
      });
    })
      .setTimeout(0)
      .on('error', (error) => {
        callback(error);
      });
    request.write(`grant_type=refresh_token&refresh_token=${encodeURI(refreshToken)}&client_id=${clientId}&client_secret=${clientSecret}`);
    request.end();
  });
};
`

**Comment by AFI4711** [comment]
**return callback** was the soltion!
