### ISSUE TITLE
netatmo.handleRequestError

### ISSUE THREAD

**Issue by cflurin** [guidone/node-red-contrib-netatmo-dashboard#4]
Hi,

I've got this error:
```sh
20 Jan 17:12:04 - [red] Uncaught Exception:
20 Jan 17:12:04 - Error: Authenticate error: Status code502
at netatmo.handleRequestError (/home/pi/.node-red/node_modules/netatmo/netatmo.js:46:15)
at .<anonymous> (/home/pi/.node-red/node_modules/netatmo/netatmo.js:115:19)
at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1081:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1001:12)
at IncomingMessage.g (events.js:286:16)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
Started Node-RED graphical event wiring tool..
20 Jan 17:12:10 - [info]
Welcome to Node-RED
===================
20 Jan 17:12:10 - [info] Node-RED version: v0.16.1
20 Jan 17:12:10 - [info] Node.js  version: v6.3.1
20 Jan 17:12:10 - [info] Linux 4.4.13-v7+ arm LE
```

is there way to catch this exception (error)?

**Comment by guidone** [comment]
Hi, looks like there's an authentication error, can you check the client id / secret and password?

Handling of the authentication error could be better though

**Comment by cflurin** [comment]
Thanks for your reply. All settings are okay, I'm using this node for weeks without any issues. Sometimes I get this `Uncaught Exception` and it disappears again. I'd like to avoid restarting of node-red and therefore I'm looking for a solution.

**Comment by cflurin** [comment]
Update: I'm testing a version with a modification. If it works in the next days, I'll upload a PR.

**Comment by guidone** [comment]
@cflurin perfect, thanks
